/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailormadeSafariRouteImport } from './routes/tailormade-safari'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortSafarisRouteImport } from './routes/short-safaris'
import { Route as LuxurySafarisRouteImport } from './routes/luxury-safaris'
import { Route as HoneymoonPackagesRouteImport } from './routes/honeymoon-packages'
import { Route as GroupToursRouteImport } from './routes/group-tours'
import { Route as ExploreOurToursRouteImport } from './routes/explore-our-tours'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BushAndBeachRouteImport } from './routes/bush-and-beach'
import { Route as BirdWatchersRouteImport } from './routes/bird-watchers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TailormadeSafariRoute = TailormadeSafariRouteImport.update({
  id: '/tailormade-safari',
  path: '/tailormade-safari',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortSafarisRoute = ShortSafarisRouteImport.update({
  id: '/short-safaris',
  path: '/short-safaris',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxurySafarisRoute = LuxurySafarisRouteImport.update({
  id: '/luxury-safaris',
  path: '/luxury-safaris',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneymoonPackagesRoute = HoneymoonPackagesRouteImport.update({
  id: '/honeymoon-packages',
  path: '/honeymoon-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupToursRoute = GroupToursRouteImport.update({
  id: '/group-tours',
  path: '/group-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreOurToursRoute = ExploreOurToursRouteImport.update({
  id: '/explore-our-tours',
  path: '/explore-our-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BushAndBeachRoute = BushAndBeachRouteImport.update({
  id: '/bush-and-beach',
  path: '/bush-and-beach',
  getParentRoute: () => rootRouteImport,
} as any)
const BirdWatchersRoute = BirdWatchersRouteImport.update({
  id: '/bird-watchers',
  path: '/bird-watchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bird-watchers': typeof BirdWatchersRoute
  '/bush-and-beach': typeof BushAndBeachRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explore-our-tours': typeof ExploreOurToursRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-packages': typeof HoneymoonPackagesRoute
  '/luxury-safaris': typeof LuxurySafarisRoute
  '/short-safaris': typeof ShortSafarisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailormade-safari': typeof TailormadeSafariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bird-watchers': typeof BirdWatchersRoute
  '/bush-and-beach': typeof BushAndBeachRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explore-our-tours': typeof ExploreOurToursRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-packages': typeof HoneymoonPackagesRoute
  '/luxury-safaris': typeof LuxurySafarisRoute
  '/short-safaris': typeof ShortSafarisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailormade-safari': typeof TailormadeSafariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tours': typeof ToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bird-watchers': typeof BirdWatchersRoute
  '/bush-and-beach': typeof BushAndBeachRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explore-our-tours': typeof ExploreOurToursRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-packages': typeof HoneymoonPackagesRoute
  '/luxury-safaris': typeof LuxurySafarisRoute
  '/short-safaris': typeof ShortSafarisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailormade-safari': typeof TailormadeSafariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bird-watchers'
    | '/bush-and-beach'
    | '/contact'
    | '/destinations'
    | '/explore-our-tours'
    | '/group-tours'
    | '/honeymoon-packages'
    | '/luxury-safaris'
    | '/short-safaris'
    | '/sitemap.xml'
    | '/tailormade-safari'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/blog/'
    | '/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bird-watchers'
    | '/bush-and-beach'
    | '/contact'
    | '/destinations'
    | '/explore-our-tours'
    | '/group-tours'
    | '/honeymoon-packages'
    | '/luxury-safaris'
    | '/short-safaris'
    | '/sitemap.xml'
    | '/tailormade-safari'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/blog'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bird-watchers'
    | '/bush-and-beach'
    | '/contact'
    | '/destinations'
    | '/explore-our-tours'
    | '/group-tours'
    | '/honeymoon-packages'
    | '/luxury-safaris'
    | '/short-safaris'
    | '/sitemap.xml'
    | '/tailormade-safari'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/blog/'
    | '/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BirdWatchersRoute: typeof BirdWatchersRoute
  BushAndBeachRoute: typeof BushAndBeachRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  ExploreOurToursRoute: typeof ExploreOurToursRoute
  GroupToursRoute: typeof GroupToursRoute
  HoneymoonPackagesRoute: typeof HoneymoonPackagesRoute
  LuxurySafarisRoute: typeof LuxurySafarisRoute
  ShortSafarisRoute: typeof ShortSafarisRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TailormadeSafariRoute: typeof TailormadeSafariRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailormade-safari': {
      id: '/tailormade-safari'
      path: '/tailormade-safari'
      fullPath: '/tailormade-safari'
      preLoaderRoute: typeof TailormadeSafariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-safaris': {
      id: '/short-safaris'
      path: '/short-safaris'
      fullPath: '/short-safaris'
      preLoaderRoute: typeof ShortSafarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-safaris': {
      id: '/luxury-safaris'
      path: '/luxury-safaris'
      fullPath: '/luxury-safaris'
      preLoaderRoute: typeof LuxurySafarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeymoon-packages': {
      id: '/honeymoon-packages'
      path: '/honeymoon-packages'
      fullPath: '/honeymoon-packages'
      preLoaderRoute: typeof HoneymoonPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-tours': {
      id: '/group-tours'
      path: '/group-tours'
      fullPath: '/group-tours'
      preLoaderRoute: typeof GroupToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-our-tours': {
      id: '/explore-our-tours'
      path: '/explore-our-tours'
      fullPath: '/explore-our-tours'
      preLoaderRoute: typeof ExploreOurToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bush-and-beach': {
      id: '/bush-and-beach'
      path: '/bush-and-beach'
      fullPath: '/bush-and-beach'
      preLoaderRoute: typeof BushAndBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bird-watchers': {
      id: '/bird-watchers'
      path: '/bird-watchers'
      fullPath: '/bird-watchers'
      preLoaderRoute: typeof BirdWatchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BirdWatchersRoute: BirdWatchersRoute,
  BushAndBeachRoute: BushAndBeachRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  ExploreOurToursRoute: ExploreOurToursRoute,
  GroupToursRoute: GroupToursRoute,
  HoneymoonPackagesRoute: HoneymoonPackagesRoute,
  LuxurySafarisRoute: LuxurySafarisRoute,
  ShortSafarisRoute: ShortSafarisRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TailormadeSafariRoute: TailormadeSafariRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
